#-*- coding : latin1 -*
import os

alphabet = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n",
            "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z", " ", "é", "è", 
            "ë", "ï", "ç", "-", "'", "ü", "ö", "ù"]

pays = ["Afrique du sud",
"Afghanistan",
"Albanie",
"Algérie",
"Allemagne",
"Andorre",
"Angleterre"
"Angola",
"Antigua-et-barbuda",
"Arabie saoudite",
"Argentine",
"Arménie",
"Australie",
"Autriche",
"Azerbaïdjan",
"Bahamas",
"Bahreïn",
"Bangladesh",
"Barbade",
"Belgique",
"Belize",
"Bénin",
"Bhoutan",
"Biélorussie",
"Birmanie",
"Bolivie",
"Bosnie-herzégovine",
"Botswana",
"Brésil",
"Brunei",
"Bulgarie",
"Burkina faso",
"Burundi",
"Cambodge",
"Cameroun",
"Canada",
"Cap-vert",
"Chili",
"Chine",
"Chypre",
"Colombie",
"Comores",
"congo",
"Corée du nord",
"Corée du sud",
"Costa rica",
"Côte d’ivoire",
"Croatie",
"Cuba",
"Danemark",
"Djibouti",
"Dominique",
"Égypte",
"Émirats arabes unis",
"États unis d'amerique",
"Équateur",
"Érythrée",
"Espagne",
"Eswatini",
"Estonie",
"États-unis",
"Éthiopie",
"Fidji",
"Finlande",
"France",
"Gabon",
"Gambie",
"Géorgie",
"Ghana",
"Grèce",
"Grenade",
"Guatemala",
"Guinée",
"Guinée équatoriale",
"Guinée-bissau",
"Guyana",
"Haïti",
"Honduras",
"Hongrie",
"Îles cook",
"Îles marshall",
"Inde",
"Indonésie",
"Irak",
"Iran",
"Irlande",
"Islande",
"Israël",
"Italie",
"Jamaïque",
"Japon",
"Jordanie",
"Kazakhstan",
"Kenya",
"Kirghizistan",
"Kiribati",
"Koweït",
"Laos",
"Lesotho",
"Lettonie",
"Liban",
"Liberia",
"Libye",
"Liechtenstein",
"Lituanie",
"Luxembourg",
"Macédoine",
"Madagascar",
"Malaisie",
"Malawi",
"Maldives",
"Mali",
"Malte",
"Maroc",
"Maurice",
"Mauritanie",
"Mexique",
"Micronésie",
"Moldavie",
"Monaco",
"Mongolie",
"Monténégro",
"Mozambique",
"Namibie",
"Nauru",
"Népal",
"Nicaragua",
"Niger",
"Nigeria",
"Niue",
"Norvège",
"Nouvelle-zélande",
"Oman",
"Ouganda",
"Ouzbékistan",
"Ouzbékistan",
"Pakistan",
"Palaos",
"Palestine",
"Panama",
"Papouasie-nouvelle-guinée",
"Paraguay",
"Pays-bas",
"Pérou",
"Philippines",
"Pologne",
"Portugal",
"Qatar",
"République centrafricaine",
"République démocratique du congo",
"République dominicaine",
"République du congo",
"République tchèque",
"Roumanie",
"Royaume-uni",
"Russie",
"Rwanda",
"Saint-kitts-et-nevis",
"Saint-vincent-et-les-grenadines",
"Sainte-lucie",
"Saint-marin",
"Salomon",
"Salvador",
"Samoa",
"São tomé-et-principe",
"Sénégal",
"Serbie",
"Seychelles",
"Sierra leone",
"Singapour",
"Slovaquie",
"Slovénie",
"Somalie",
"Soudan",
"Soudan du sud",
"Sri lanka",
"Suède",
"Suisse",
"Suriname",
"Syrie",
"Tadjikistan",
"Tanzanie",
"Tchad",
"Thaïlande",
"Timor oriental",
"Togo",
"Tonga",
"Trinité-et-tobago",
"Tunisie",
"Turkménistan",
"Turquie",
"Tuvalu",
"Ukraine",
"Uruguay",
"Vanuatu",
"Vatican",
"Venezuela",
"Viêt nam",
"Yémen",
"Zambie",
"Zimbabwe"]

if __name__ == "__main__" :
    print(pays)

os.system("pause")
